blog_website/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class post_form(FlaskForm):
    title=StringField('Title',validators=[DataRequired()])
    content=TextAreaField('Content',validators=[DataRequired()])
    submit=SubmitField('Post')

blog_website/posts/routes.py
from flask import Blueprint

posts=Blueprint('posts',__name__)

from flask import render_template,redirect,flash,url_for,abort
from blog_website.models import Personalinfo,Logininfo,Post
from flask_login import current_user,login_required
from blog_website.posts.forms import post_form
from blog_website.users.forms import update_form,update_post_form
from blog_website.users.utils import save_picture
from blog_website import db

@posts.route("/create_post",methods=['get','post'])
@login_required
def create_post():
    form=post_form()
    if form.validate_on_submit():
        post=Post(title=form.title.data,content=form.content.data,author_name=current_user.username)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created successfully!")
        return redirect(url_for('main.home',page_num=1))
    return render_template("create_post.html",title="New Post",form=form)


@posts.route("/post/<post_id>")
def post(post_id):
    post=Post.query.get_or_404(post_id)
    return render_template("post.html",post=post)

@posts.route("/post/<post_id>/update",methods=['get','post'])
@login_required
def update_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author_name!=current_user.username:
        abort(403)
    form=update_post_form()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash("Your post has been successfully updated!")
        return redirect(url_for('posts.post',post_id=post.id))
    form.title.data=post.title
    form.content.data=post.content
    return render_template("update_post.html",post=post,form=form)

@posts.route("/post/<post_id>/delete",methods=['get','post'])
@login_required
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author_name!=current_user.username:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been successfully deleted!")
    return redirect(url_for('main.home',page_num=1))

blog_website/users/routes.py
from flask import Blueprint

users=Blueprint('users',__name__)

from flask import render_template,redirect,request,url_for,flash,abort
import os
from flask_login import current_user,login_required,login_user,logout_user
from blog_website.models import Logininfo,Personalinfo,Post
from blog_website.users.forms import signin_form,signup_form,reset_password_form,forgot_password_form,update_form
from blog_website import bcrypt,db,login_manager
from blog_website.users.utils import send_reset_email,save_picture

@login_manager.user_loader 
def load_user(user_id):
    return Logininfo.query.get(int(user_id))

@users.route("/signin",methods=['post','get'])
def signin():
    form=signin_form()
    if current_user.is_authenticated:
        return redirect(url_for('main.home',page_num=1))
    if form.validate_on_submit():
        user=Logininfo.query.filter_by(email=form.email.data).first()
        if not user:
            flash("You have entered incorrect email address.Please try again!")
            return redirect(url_for('users.signin'))
        if not bcrypt.check_password_hash(user.password,form.password.data):
            flash("You have entered incorrect password.Please try again!")
            return redirect(url_for('users.signin'))
        login_user(user,remember=form.remember_me.data)
        next_page=request.args.get('next')
        if next_page:
            return redirect(next_page)
        else:
            return redirect(url_for('main.home',page_num=1))
    return render_template("signin.html",title="SignIn",form=form)

@users.route("/signup",methods=['post','get'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home',page_num=1))
    form=signup_form()
    if form.validate_on_submit():
        user=Logininfo.query.filter_by(username=form.username.data).first()
        if user:
            flash("This Username is taken.Please use different!")
            return redirect(url_for('users.signup'))
        user=Logininfo.query.filter_by(email=form.email.data).first()
        if user:
            flash("This Email is taken.Please use different!")
            return redirect(url_for('users.signup'))
        hashed_password=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=Logininfo(username=form.username.data,email=form.email.data,password=hashed_password)
        user_info=Personalinfo(account=user)
        db.session.add(user)
        db.session.add(user_info)
        db.session.commit()
        flash("Your Account has been created successfully!Please Login to explore the world inside...")
        return redirect(url_for('main.success'))
    return render_template("signup.html",title="SignUp",form=form)

@users.route("/signout")
@login_required
def signout():
    logout_user()
    return redirect(url_for('users.signin'))

@users.route("/account")
@login_required
def account():
    current_profile=Personalinfo.query.get(current_user.username)
    image_file=url_for('static',filename='profile_pics/'+current_profile.picture)
    return render_template("account.html",title="Account",image_file=image_file,current_profile=current_profile)

@users.route("/user/<string:username>/<int:page>")
@login_required
def user_posts(username,page):
    posts=Post.query.filter_by(author_name=username).order_by(Post.date_posted.desc()).paginate(per_page=5,page=page)
    return render_template("user_posts.html",title=username+" Posts",posts=posts,username=username)

@users.route("/forgot_password",methods=['get','post'])
def forgot_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home',page_num=1))
    form=forgot_password_form()
    if form.validate_on_submit():
        user=Logininfo.query.filter_by(email=form.email.data).first()
        if user is None:
            flash("Account with email "+form.email.data+" does not exist.Please create an account first.")
            return redirect(url_for('users.signup'))
        send_reset_email(user)
        flash("An mail has been sent to your email with instruction to reset your password.")
        return redirect(url_for('users.signin'))
    return render_template("forgot_password.html",title="Forgot Password",form=form)

@users.route("/reset_password/<token>",methods=['get','post'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home',page_num=1))
    user=Logininfo.verify_reset_token(token)
    if user is None:
        flash("The email sent is invalid or expired.")
        return redirect(url_for('users.forgot_password'))
    form=reset_password_form()
    if form.validate_on_submit():
        hashed_password=bcrypt.generate_password_hash(form.password.data)
        user.password=hashed_password
        db.session.commit()
        flash("Your password has been reset successfully! Sign in now...")
        return redirect(url_for('users.signin'))
    return render_template("reset_password.html",title="Reset Password",form=form,id=user.id)

@users.route("/update",methods=['get','post'])
@login_required
def update():
    current_profile=Personalinfo.query.filter_by(user_id=current_user.username).first()
    form=update_form()
    if form.validate_on_submit():
        if current_user.username==form.username.data:
            pass
        else:
            user=Logininfo.query.filter_by(username=form.username.data).first()
            if user:
                flash("This username is already taken!Choose different")
                return redirect(url_for('users.update'))
            else:
                items=Post.query.filter_by(author_name=current_user.username).all()
                for item in items:
                    item.author_name=form.username.data
                current_user.username=form.username.data
                current_profile.user_id=form.username.data
        
        if current_user.email==form.email.data:
            pass
        else:
            user=Logininfo.query.filter_by(email=form.email.data).first()
            if user:
                flash("This email is already taken!Choose different")
                return redirect(url_for('users.update'))
            else:
                current_user.email=form.email.data
        if form.picture.data:
            picture_file=save_picture(form.picture.data)
            if current_profile.picture!='default.jpg':
                file_path=os.getcwd()+"/blog_website/static/profile_pics/"+current_profile.picture
                if os.path.isfile(file_path):
                    os.remove(file_path)
            current_profile.picture=picture_file
        if form.firstname.data:
            current_profile.firstname=form.firstname.data
        else:
            current_profile.firstname="--N/A--"
        if form.lastname.data:
            current_profile.lastname=form.lastname.data
        else:
            current_profile.lastname="--N/A--"
        if form.country.data:
            current_profile.country=form.country.data
        else:
            current_profile.country="--N/A--"
        if form.bio.data:
            current_profile.bio=form.bio.data
        else:
            current_profile.bio="--N/A--"
        current_profile.dob=form.dob.data
        current_profile.gender=form.gender.data          
        db.session.commit()
        flash("Your account information has been updated successfully.","success")
        return redirect(url_for('users.account'))
    form.username.data=current_profile.user_id
    form.email.data=current_profile.account.email
    form.firstname.data=current_profile.firstname
    form.lastname.data=current_profile.lastname
    form.dob.data=current_profile.dob
    form.bio.data=current_profile.bio
    form.gender.data=current_profile.gender
    form.country.data=current_profile.country 
    return render_template("update_info.html",form=form,current_profile=current_profile)

@users.route("/delete_account/<int:id>",methods=['post'])
@login_required
def delete_account(id):
    logout_user()
    user=Logininfo.query.get(id)
    info=Personalinfo.query.filter_by(user_id=user.username).first()
    pic=info.picture
    if pic!='default.jpg':
        file_path=os.getcwd()+"/blog_website/static/profile_pics/"+pic
        if os.path.isfile(file_path):
            os.remove(file_path)
    db.session.delete(user)
    db.session.commit()
    flash("Your account has been deleted permanently.SignUp to Continue...")
    return redirect(url_for('users.signup'))

blog_website/templates/account.html
{%extends "base.html"%} 
{%block content%}  
        <div class="content-section">
                <div class="media">
                <img class="rounded-circle account-img" src="{{image_file}}">
                        <div class="media-body">
                                <div class="card mb-3">
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-sm-3">
                                        <h6 class="mb-0">Username</h6>
                                      </div>
                                      <div class="col-sm-9 text-secondary">
                                        {{current_profile.user_id}}
                                      </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                      <div class="col-sm-3">
                                        <h6 class="mb-0">Email</h6>
                                      </div>
                                      <div class="col-sm-9 text-secondary">
                                        {{current_profile.account.email}}
                                      </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                      <div class="col-sm-3">
                                        <h6 class="mb-0">Firstname</h6>
                                      </div>
                                      <div class="col-sm-9 text-secondary">
                                        {{current_profile.firstname}}
                                      </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                      <div class="col-sm-3">
                                        <h6 class="mb-0">Lastname</h6>
                                      </div>
                                      <div class="col-sm-9 text-secondary">
                                        {{current_profile.lastname}}
                                      </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                      <div class="col-sm-3">
                                        <h6 class="mb-0">Gender</h6>
                                      </div>
                                      <div class="col-sm-9 text-secondary">
                                        {{current_profile.gender}}
                                      </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                          <h6 class="mb-0">Country</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                          {{current_profile.country}}
                                        </div>
                                      </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                          <h6 class="mb-0">Date of Birth</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                          {{current_profile.dob}}
                                        </div>
                                      </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                          <h6 class="mb-0">Bio</h6>
                                        </div>
                                        <div class="col-sm-9 text-secondary">
                                          {{current_profile.bio}}
                                        </div>
                                      </div>
                                    <hr>
                                    <div class="row">
                                      <div class="col-sm-12 d-flex justify-content-between">
                                        <a class="btn btn-info"  href="{{url_for('users.update')}}">UPDATE PROFILE</a>
                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">DELETE ACCOUNT</button>
                                      </div>
                                    </div>
                                  </div>
                                </div> 
                        </div>
                </div>
        </div>
        <!-- Model -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">PERMANENTLY DELETE ACCOUNT?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Are you sure to permanently delete the account? Once the account is deleted 
                  all your personal information and posts will be lost and will not be recovered.
                </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCLE</button>
                <form action="{{url_for('users.delete_account',id=current_profile.account.id)}}" method="post">
                  <input class="btn btn-danger" type="submit" value="DELETE">
              </form>
              </div>
            </div>
          </div>
        </div>
{%endblock%}  

blog_website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}">
    <title>
      {% if title %}
        {{ title }}
      {% else %}
        Blog
      {% endif %}
    </title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <h2 class="navbar-brand mr-4 mt-2 h1 font-weight-bold">BLOGGER</h2>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav"> 
                <a class="nav-item nav-link" href="{{url_for('main.home',page_num=1)}}">Home</a>
                <a class="nav-item nav-link" href="{{url_for('posts.create_post')}}">Create_Post</a>
                <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                <a class="nav-item nav-link" href="{{url_for('users.signout')}}">SignOut</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8" style="margin-left: 140px;">
          <div class="alert-info">
            {%for message in get_flashed_messages()%} 
              {{message}}
            {%endfor%}
          </div>
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog_website/templates/create_post.html
{%extends "base.html"%}
{%block content%}
    <form action="{{url_for('posts.create_post')}}" method="post" >
        <fieldset>
            <legend style="text-align: center;">CREATE POST</legend>
            {{form.csrf_token}}
            {{form.title.label}}<br>
            {{form.title(class="form-control")}}<br>
            {{form.content.label}}<br>
            {{form.content(class="form-control",row='500',cols='50')}}<hr>
            <div class="text-center">
                {{form.submit(class="btn btn-primary btn-lg")}}
            </div>
        </fieldset>
    </form>
{%endblock%}

blog_website/templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%if title%} 
            {{title}}
        {%else%} 
            BLOG
        {%endif%}
    </title> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{url_for('static',filename='signin.css')}}">
</head>
<body> 
    {%if get_flashed_messages()%} 
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {%for message in get_flashed_messages()%} 
                {{message}}
            {%endfor%}
        </div>
    {%endif%}
    <div class="signup-form">
        <form action="" method="post">
            {{ form.csrf_token }}
            <hr>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fa fa-paper-plane"></i>
                        </span>                    
                    </div>
                    {{form.email(class="form-control",placeholder="Enter Email address")}}
                    {%for error in form.email.errors%} 
                        {{error}}
                    {%endfor%}
                </div>
            </div>        
            <div class="form-group">
                {{form.submit(class="btn btn-primary btn-lg")}}
            </div>
        </form>
    </div>
</body>
</html>

blog_website/templates/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%if title%} 
            {{title}}
        {%else%} 
            BLOG
        {%endif%}
    </title>
    <link rel="stylesheet" href="{{url_for('static',filename='greeting.css')}}">
</head>
<body>
    <div class="congo">
        <div class="upper">
            <h1>CONGRATULATION</h1>
        </div>
        <hr>
        <div class="lower">
            <section>
                <p>
                    {%for message in get_flashed_messages()%} 
                        {{message}}
                    {%endfor%}
                </p>
            </section>
            <span>
                <a href="{{url_for('users.signin')}}">
                    CONTINUE
                </a>
            </span>
        </div>
    </div>
</body>
</html>

blog_website/templates/home.html
{%extends "base.html"%} 
{%block content%}  
    {% for post in posts.items%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{url_for('static',filename='profile_pics/'+post.author.picture)}}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_posts',username=post.author_name,page=1)}}">{{ post.author_name }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
                <h5><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h5>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {%endfor%}
    {%for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=2,right_current=2)%}
        {%if page_num%}
            {%if posts.page==page_num%}
                <a class="btn btn-info mb-4" href="{{url_for('main.home',page_num=page_num)}}">{{page_num}}</a>
            {%else%}
                <a class="btn btn-outline-info mb-4" href="{{url_for('main.home',page_num=page_num)}}">{{page_num}}</a>
            {%endif%}
        {%else%} 
            ... 
        {%endif%}
    {%endfor%}
{%endblock%}  

blog_website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%if title%} 
            {{title}}
        {%else%} 
            BLOG
        {%endif%}
    </title> 
    <link rel="stylesheet" href="{{url_for('static',filename='main.css')}}">
</head>
<body> 
    <header>
        <nav class="navbar">
            <div class="logo font-weight-bold">
                BLOGGER
            </div>
            <div class="info">
                <a href="{{url_for('users.signup')}}">SignUp</a>
                <a href="{{url_for('users.signin')}}">SignIn</a>
            </div>
        </nav>
        <section class="h-text">
            <h1>Let the world know what you know...</h1>
            <br>
            <a href="{{url_for('users.signin')}}">Create Your Blog</a>
        </section>
    </header>
</body>
</html>

blog_website/templates/post.html
{%extends "base.html"%} 
{%block content%}  
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{url_for('static',filename='profile_pics/'+post.author.picture)}}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{url_for('users.user_posts',username=post.author_name,page=1)}}">{{ post.author_name }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
            {%if post.author_name==current_user.username%}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post',post_id=post.id)}}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1 " data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {%endif%}
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="post">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
{%endblock%} 

blog_website/templates/update_post.html
{%extends "base.html"%}
{%block content%}
    <form action="{{url_for('posts.update_post',post_id=post.id)}}" method="post" >
        <fieldset>
            <legend style="text-align: center;">UPDATE POST</legend>
            {{form.csrf_token}}
            {{form.title.label}}<br>
            {{form.title(class="form-control")}}<br>
            {{form.content.label}}<br>
            {{form.content(class="form-control",row='500',cols='50')}}<hr>
            <div class="text-center">
                {{form.submit(class="btn btn-primary btn-lg")}}
            </div>
        </fieldset>
    </form>
{%endblock%}

blog_website/templates/user_posts.html
{%extends "base.html"%} 
{%block content%}  
    {% for post in posts.items%}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{url_for('static',filename='profile_pics/'+post.author.picture)}}">
            <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_posts',username=post.author_name,page=1)}}">{{ post.author_name }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
                <h5><a class="article-title" href="{{url_for('posts.post',post_id=post.id)}}">{{ post.title }}</a></h5>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {%endfor%}
    {%for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=2,right_current=2)%}
        {%if page_num%}
            {%if posts.page==page_num%}
                <a class="btn btn-info mb-4" href="{{url_for('users.user_posts',username=username,page=page_num)}}">{{page_num}}</a>
            {%else%}
                <a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts',username=username,page=page_num)}}">{{page_num}}</a>
            {%endif%}
        {%else%} 
            ... 
        {%endif%}
    {%endfor%}
{%endblock%}  